#include "UniverseFastestLibrary.h"

#if( ( defined __MS_VCXX__ ) && ( defined __RELEASE__ ) )

//以下文件不包含memcpy和memmove：vcruntime140_1.dll、vcruntime140_1d.dll、vcruntime140_1_app.dll、vcruntime140_1_clr0400.dll、vcruntime140_threads.dll、vcruntime140_threadsd.dll

#define VcRuntimeDllName "vcruntime140_src" //x86对应C:\Windows\SysWOW64\vcruntime140.dll、x64对应C:\Windows\System32\vcruntime140.dll。
//#define VcRuntimeDllName "vcruntime140_clr0400_src" //x86对应C:\Windows\SysWOW64\vcruntime140_clr0400.dll、x64对应C:\Windows\System32\vcruntime140_clr0400.dll。
//#define VcRuntimeDllName "vcruntime140_app_src" //x64对应C:\Windows\SystemApps\MicrosoftWindows.Client.CoreAI_cw5n1h2txyewy\vcruntime140_app.dll。
//#define VcRuntimeDllName "vcruntime140_cor3_src" //对应vcruntime140_cor3.dll。

//调用进程：explorer.exe、CrossDeviceService.exe、devenv.exe

#if( defined __X86__ ) //特别注意：x86下的带_前缀的符号编译器会删除一个_，所以要多加一个_。

#pragma comment(linker, "/export:__CreateFrameInfo=" VcRuntimeDllName "._CreateFrameInfo")
#pragma comment(linker, "/export:__CxxThrowException=" VcRuntimeDllName "._CxxThrowException")
#pragma comment(linker, "/export:__EH_prolog=" VcRuntimeDllName "._EH_prolog")
#pragma comment(linker, "/export:__FindAndUnlinkFrame=" VcRuntimeDllName "._FindAndUnlinkFrame")
#pragma comment(linker, "/export:__IsExceptionObjectToBeDestroyed=" VcRuntimeDllName "._IsExceptionObjectToBeDestroyed")
#pragma comment(linker, "/export:__NLG_Dispatch2=" VcRuntimeDllName "._NLG_Dispatch2")
#pragma comment(linker, "/export:__NLG_Return=" VcRuntimeDllName "._NLG_Return")
#pragma comment(linker, "/export:__NLG_Return2=" VcRuntimeDllName "._NLG_Return2")
#pragma comment(linker, "/export:__SetWinRTOutOfMemoryExceptionCallback=" VcRuntimeDllName "._SetWinRTOutOfMemoryExceptionCallback")
#pragma comment(linker, "/export:___AdjustPointer=" VcRuntimeDllName ".__AdjustPointer")
#pragma comment(linker, "/export:___BuildCatchObject=" VcRuntimeDllName ".__BuildCatchObject")
#pragma comment(linker, "/export:___BuildCatchObjectHelper=" VcRuntimeDllName ".__BuildCatchObjectHelper")
#pragma comment(linker, "/export:___CxxDetectRethrow=" VcRuntimeDllName ".__CxxDetectRethrow")
#pragma comment(linker, "/export:___CxxExceptionFilter=" VcRuntimeDllName ".__CxxExceptionFilter")
#pragma comment(linker, "/export:___CxxFrameHandler=" VcRuntimeDllName ".__CxxFrameHandler")
#pragma comment(linker, "/export:___CxxFrameHandler2=" VcRuntimeDllName ".__CxxFrameHandler2")
#pragma comment(linker, "/export:___CxxFrameHandler3=" VcRuntimeDllName ".__CxxFrameHandler3")
#pragma comment(linker, "/export:___CxxLongjmpUnwind=" VcRuntimeDllName ".__CxxLongjmpUnwind")
#pragma comment(linker, "/export:___CxxQueryExceptionSize=" VcRuntimeDllName ".__CxxQueryExceptionSize")
#pragma comment(linker, "/export:___CxxRegisterExceptionObject=" VcRuntimeDllName ".__CxxRegisterExceptionObject")
#pragma comment(linker, "/export:___CxxUnregisterExceptionObject=" VcRuntimeDllName ".__CxxUnregisterExceptionObject")
#pragma comment(linker, "/export:___DestructExceptionObject=" VcRuntimeDllName ".__DestructExceptionObject")
#pragma comment(linker, "/export:___FrameUnwindFilter=" VcRuntimeDllName ".__FrameUnwindFilter")
#pragma comment(linker, "/export:___GetPlatformExceptionInfo=" VcRuntimeDllName ".__GetPlatformExceptionInfo")
#pragma comment(linker, "/export:___RTCastToVoid=" VcRuntimeDllName ".__RTCastToVoid")
#pragma comment(linker, "/export:___RTDynamicCast=" VcRuntimeDllName ".__RTDynamicCast")
#pragma comment(linker, "/export:___RTtypeid=" VcRuntimeDllName ".__RTtypeid")
#pragma comment(linker, "/export:___TypeMatch=" VcRuntimeDllName ".__TypeMatch")
#pragma comment(linker, "/export:___current_exception=" VcRuntimeDllName ".__current_exception")
#pragma comment(linker, "/export:___current_exception_context=" VcRuntimeDllName ".__current_exception_context")
#pragma comment(linker, "/export:___intrinsic_setjmp=" VcRuntimeDllName ".__intrinsic_setjmp")
#pragma comment(linker, "/export:___processing_throw=" VcRuntimeDllName ".__processing_throw")
#pragma comment(linker, "/export:___report_gsfailure=" VcRuntimeDllName ".__report_gsfailure")
#pragma comment(linker, "/export:___std_exception_copy=" VcRuntimeDllName ".__std_exception_copy")
#pragma comment(linker, "/export:___std_exception_destroy=" VcRuntimeDllName ".__std_exception_destroy")
#pragma comment(linker, "/export:___std_terminate=" VcRuntimeDllName ".__std_terminate")
#pragma comment(linker, "/export:___std_type_info_compare=" VcRuntimeDllName ".__std_type_info_compare")
#pragma comment(linker, "/export:___std_type_info_destroy_list=" VcRuntimeDllName ".__std_type_info_destroy_list")
#pragma comment(linker, "/export:___std_type_info_hash=" VcRuntimeDllName ".__std_type_info_hash")
#pragma comment(linker, "/export:___std_type_info_name=" VcRuntimeDllName ".__std_type_info_name")
#pragma comment(linker, "/export:___telemetry_main_invoke_trigger=" VcRuntimeDllName ".__telemetry_main_invoke_trigger")
#pragma comment(linker, "/export:___telemetry_main_return_trigger=" VcRuntimeDllName ".__telemetry_main_return_trigger")
#pragma comment(linker, "/export:___unDName=" VcRuntimeDllName ".__unDName")
#pragma comment(linker, "/export:___unDNameEx=" VcRuntimeDllName ".__unDNameEx")
#pragma comment(linker, "/export:___uncaught_exception=" VcRuntimeDllName ".__uncaught_exception")
#pragma comment(linker, "/export:___uncaught_exceptions=" VcRuntimeDllName ".__uncaught_exceptions")
#pragma comment(linker, "/export:___vcrt_GetModuleFileNameW=" VcRuntimeDllName ".__vcrt_GetModuleFileNameW")
#pragma comment(linker, "/export:___vcrt_GetModuleHandleW=" VcRuntimeDllName ".__vcrt_GetModuleHandleW")
#pragma comment(linker, "/export:___vcrt_InitializeCriticalSectionEx=" VcRuntimeDllName ".__vcrt_InitializeCriticalSectionEx")
#pragma comment(linker, "/export:___vcrt_LoadLibraryExW=" VcRuntimeDllName ".__vcrt_LoadLibraryExW")
#pragma comment(linker, "/export:__chkesp=" VcRuntimeDllName "._chkesp")
#pragma comment(linker, "/export:__except_handler2=" VcRuntimeDllName "._except_handler2")
#pragma comment(linker, "/export:__except_handler3=" VcRuntimeDllName "._except_handler3")
#pragma comment(linker, "/export:__except_handler4_common=" VcRuntimeDllName "._except_handler4_common")
#pragma comment(linker, "/export:__get_purecall_handler=" VcRuntimeDllName "._get_purecall_handler")
#pragma comment(linker, "/export:__get_unexpected=" VcRuntimeDllName "._get_unexpected")
#pragma comment(linker, "/export:__global_unwind2=" VcRuntimeDllName "._global_unwind2")
#pragma comment(linker, "/export:__is_exception_typeof=" VcRuntimeDllName "._is_exception_typeof")
#pragma comment(linker, "/export:__local_unwind2=" VcRuntimeDllName "._local_unwind2")
#pragma comment(linker, "/export:__local_unwind4=" VcRuntimeDllName "._local_unwind4")
#pragma comment(linker, "/export:__longjmpex=" VcRuntimeDllName "._longjmpex")
#pragma comment(linker, "/export:__purecall=" VcRuntimeDllName "._purecall")
#pragma comment(linker, "/export:__seh_longjmp_unwind4=" VcRuntimeDllName "._seh_longjmp_unwind4")
#pragma comment(linker, "/export:__seh_longjmp_unwind=" VcRuntimeDllName "._seh_longjmp_unwind")
#pragma comment(linker, "/export:__set_purecall_handler=" VcRuntimeDllName "._set_purecall_handler")
#pragma comment(linker, "/export:__set_se_translator=" VcRuntimeDllName "._set_se_translator")
#pragma comment(linker, "/export:__setjmp3=" VcRuntimeDllName "._setjmp3")
#pragma comment(linker, "/export:longjmp=" VcRuntimeDllName ".longjmp")
#pragma comment(linker, "/export:memchr=" VcRuntimeDllName ".memchr")
#pragma comment(linker, "/export:memcmp=" VcRuntimeDllName ".memcmp")
//#pragma comment(linker, "/export:memcpy=" VcRuntimeDllName ".memcpy")
//#pragma comment(linker, "/export:memmove=" VcRuntimeDllName ".memmove")
#pragma comment(linker, "/export:memset=" VcRuntimeDllName ".memset")
#pragma comment(linker, "/export:set_unexpected=" VcRuntimeDllName ".set_unexpected")
#pragma comment(linker, "/export:strchr=" VcRuntimeDllName ".strchr")
#pragma comment(linker, "/export:strrchr=" VcRuntimeDllName ".strrchr")
#pragma comment(linker, "/export:strstr=" VcRuntimeDllName ".strstr")
#pragma comment(linker, "/export:unexpected=" VcRuntimeDllName ".unexpected")
#pragma comment(linker, "/export:wcschr=" VcRuntimeDllName ".wcschr")
#pragma comment(linker, "/export:wcsrchr=" VcRuntimeDllName ".wcsrchr")
#pragma comment(linker, "/export:wcsstr=" VcRuntimeDllName ".wcsstr")

#elif( defined __X64__ )

#pragma comment(linker, "/export:_CreateFrameInfo=" VcRuntimeDllName "._CreateFrameInfo")
#pragma comment(linker, "/export:_CxxThrowException=" VcRuntimeDllName "._CxxThrowException")
#pragma comment(linker, "/export:_FindAndUnlinkFrame=" VcRuntimeDllName "._FindAndUnlinkFrame")
#pragma comment(linker, "/export:_IsExceptionObjectToBeDestroyed=" VcRuntimeDllName "._IsExceptionObjectToBeDestroyed")
#pragma comment(linker, "/export:_SetWinRTOutOfMemoryExceptionCallback=" VcRuntimeDllName "._SetWinRTOutOfMemoryExceptionCallback")
#pragma comment(linker, "/export:__AdjustPointer=" VcRuntimeDllName ".__AdjustPointer")
#pragma comment(linker, "/export:__BuildCatchObject=" VcRuntimeDllName ".__BuildCatchObject")
#pragma comment(linker, "/export:__BuildCatchObjectHelper=" VcRuntimeDllName ".__BuildCatchObjectHelper")
#pragma comment(linker, "/export:__C_specific_handler=" VcRuntimeDllName ".__C_specific_handler")
#pragma comment(linker, "/export:__C_specific_handler_noexcept=" VcRuntimeDllName ".__C_specific_handler_noexcept")
#pragma comment(linker, "/export:__CxxDetectRethrow=" VcRuntimeDllName ".__CxxDetectRethrow")
#pragma comment(linker, "/export:__CxxExceptionFilter=" VcRuntimeDllName ".__CxxExceptionFilter")
#pragma comment(linker, "/export:__CxxFrameHandler=" VcRuntimeDllName ".__CxxFrameHandler")
#pragma comment(linker, "/export:__CxxFrameHandler2=" VcRuntimeDllName ".__CxxFrameHandler2")
#pragma comment(linker, "/export:__CxxFrameHandler3=" VcRuntimeDllName ".__CxxFrameHandler3")
#pragma comment(linker, "/export:__CxxQueryExceptionSize=" VcRuntimeDllName ".__CxxQueryExceptionSize")
#pragma comment(linker, "/export:__CxxRegisterExceptionObject=" VcRuntimeDllName ".__CxxRegisterExceptionObject")
#pragma comment(linker, "/export:__CxxUnregisterExceptionObject=" VcRuntimeDllName ".__CxxUnregisterExceptionObject")
#pragma comment(linker, "/export:__DestructExceptionObject=" VcRuntimeDllName ".__DestructExceptionObject")
#pragma comment(linker, "/export:__FrameUnwindFilter=" VcRuntimeDllName ".__FrameUnwindFilter")
#pragma comment(linker, "/export:__GetPlatformExceptionInfo=" VcRuntimeDllName ".__GetPlatformExceptionInfo")
#pragma comment(linker, "/export:__NLG_Dispatch2=" VcRuntimeDllName ".__NLG_Dispatch2")
#pragma comment(linker, "/export:__NLG_Return2=" VcRuntimeDllName ".__NLG_Return2")
#pragma comment(linker, "/export:__RTCastToVoid=" VcRuntimeDllName ".__RTCastToVoid")
#pragma comment(linker, "/export:__RTDynamicCast=" VcRuntimeDllName ".__RTDynamicCast")
#pragma comment(linker, "/export:__RTtypeid=" VcRuntimeDllName ".__RTtypeid")
#pragma comment(linker, "/export:__TypeMatch=" VcRuntimeDllName ".__TypeMatch")
#pragma comment(linker, "/export:__current_exception=" VcRuntimeDllName ".__current_exception")
#pragma comment(linker, "/export:__current_exception_context=" VcRuntimeDllName ".__current_exception_context")
#pragma comment(linker, "/export:__intrinsic_setjmp=" VcRuntimeDllName ".__intrinsic_setjmp")
#pragma comment(linker, "/export:__intrinsic_setjmpex=" VcRuntimeDllName ".__intrinsic_setjmpex")
#pragma comment(linker, "/export:__processing_throw=" VcRuntimeDllName ".__processing_throw")
#pragma comment(linker, "/export:__report_gsfailure=" VcRuntimeDllName ".__report_gsfailure")
#pragma comment(linker, "/export:__std_exception_copy=" VcRuntimeDllName ".__std_exception_copy")
#pragma comment(linker, "/export:__std_exception_destroy=" VcRuntimeDllName ".__std_exception_destroy")
#pragma comment(linker, "/export:__std_terminate=" VcRuntimeDllName ".__std_terminate")
#pragma comment(linker, "/export:__std_type_info_compare=" VcRuntimeDllName ".__std_type_info_compare")
#pragma comment(linker, "/export:__std_type_info_destroy_list=" VcRuntimeDllName ".__std_type_info_destroy_list")
#pragma comment(linker, "/export:__std_type_info_hash=" VcRuntimeDllName ".__std_type_info_hash")
#pragma comment(linker, "/export:__std_type_info_name=" VcRuntimeDllName ".__std_type_info_name")
#pragma comment(linker, "/export:__telemetry_main_invoke_trigger=" VcRuntimeDllName ".__telemetry_main_invoke_trigger")
#pragma comment(linker, "/export:__telemetry_main_return_trigger=" VcRuntimeDllName ".__telemetry_main_return_trigger")
#pragma comment(linker, "/export:__unDName=" VcRuntimeDllName ".__unDName")
#pragma comment(linker, "/export:__unDNameEx=" VcRuntimeDllName ".__unDNameEx")
#pragma comment(linker, "/export:__uncaught_exception=" VcRuntimeDllName ".__uncaught_exception")
#pragma comment(linker, "/export:__uncaught_exceptions=" VcRuntimeDllName ".__uncaught_exceptions")
#pragma comment(linker, "/export:__vcrt_GetModuleFileNameW=" VcRuntimeDllName ".__vcrt_GetModuleFileNameW")
#pragma comment(linker, "/export:__vcrt_GetModuleHandleW=" VcRuntimeDllName ".__vcrt_GetModuleHandleW")
#pragma comment(linker, "/export:__vcrt_InitializeCriticalSectionEx=" VcRuntimeDllName ".__vcrt_InitializeCriticalSectionEx")
#pragma comment(linker, "/export:__vcrt_LoadLibraryExW=" VcRuntimeDllName ".__vcrt_LoadLibraryExW")
#pragma comment(linker, "/export:_get_purecall_handler=" VcRuntimeDllName "._get_purecall_handler")
#pragma comment(linker, "/export:_get_unexpected=" VcRuntimeDllName "._get_unexpected")
#pragma comment(linker, "/export:_is_exception_typeof=" VcRuntimeDllName "._is_exception_typeof")
#pragma comment(linker, "/export:_local_unwind=" VcRuntimeDllName "._local_unwind")
#pragma comment(linker, "/export:_purecall=" VcRuntimeDllName "._purecall")
#pragma comment(linker, "/export:_set_purecall_handler=" VcRuntimeDllName "._set_purecall_handler")
#pragma comment(linker, "/export:_set_se_translator=" VcRuntimeDllName "._set_se_translator")
#pragma comment(linker, "/export:__std_type_info_name=" VcRuntimeDllName ".__std_type_info_name")
#pragma comment(linker, "/export:longjmp=" VcRuntimeDllName ".longjmp")
#pragma comment(linker, "/export:memchr=" VcRuntimeDllName ".memchr")
#pragma comment(linker, "/export:memcmp=" VcRuntimeDllName ".memcmp")
//#pragma comment(linker, "/export:memcpy=" VcRuntimeDllName ".memcpy")
//#pragma comment(linker, "/export:memmove=" VcRuntimeDllName ".memmove")
#pragma comment(linker, "/export:memset=" VcRuntimeDllName ".memset")
#pragma comment(linker, "/export:set_unexpected=" VcRuntimeDllName ".set_unexpected")
#pragma comment(linker, "/export:strchr=" VcRuntimeDllName ".strchr")
#pragma comment(linker, "/export:strrchr=" VcRuntimeDllName ".strrchr")
#pragma comment(linker, "/export:strstr=" VcRuntimeDllName ".strstr")
#pragma comment(linker, "/export:unexpected=" VcRuntimeDllName ".unexpected")
#pragma comment(linker, "/export:wcschr=" VcRuntimeDllName ".wcschr")
#pragma comment(linker, "/export:wcsrchr=" VcRuntimeDllName ".wcsrchr")
#pragma comment(linker, "/export:wcsstr=" VcRuntimeDllName ".wcsstr")

#endif

#endif

//留一个空的源文件在这里，是为了防止MSVC++编译动态库时报错error LNK2001: 无法解析的外部符号 __DllMainCRTStartup@12。